### ISSUE TITLE
Add a logo for this repository

### ISSUE THREAD

**Issue by TheAdnan** [TheAdnan/hashr#5]
Create a fancy logo for this repository.
_Note_: PR to the `hacktober` branch.

**Comment by stefanobg** [comment]
I can work on that!

Is there anything you were thinking about, maybe some inspiration?

**Comment by TheAdnan** [comment]
No, feel free to tinker and experiment :cat2:

**Comment by stefanobg** [comment]
Done, friend!

Take a look on [my fork ](https://github.com/stefanobg/hashr)to analyse and check the [PR](https://github.com/TheAdnan/hashr/pull/27) :)
